[package]
name = "rusty_webex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
http = "0.2.9"
log = "0.4.18"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
